### ISSUE TITLE
Array port schema representation

### ISSUE THREAD

**Issue by emil14** [nevalang/neva#10]
Array port defenition

1)

```yaml
portName[]: int
```
2)

```yaml
portName:
  type: int
  arr: true # optional
```

3) 

```yaml
portName: int[]
```

Array port reference:

1.

```
node:
  outport[0]:
    node:
      - inport[0]
      - inport[1]
```
