### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by emil14** [nevalang/neva#39]
FBP has lots of generic components like `Select` or `Count`. Current implementation assumes compile-time type-checking so there must be a concept of generic types.

Goals:

- No `any`
- Nested expressions `X<Y<Z>>`

---

## How to resolve generics between two components in a scope?

```yaml
deps:
    me:
        io:
            arg:
                T
            in:
                l:
                    in:
                        type: list
                        args: [T]
            
io:
    arg:
        T
    in:
        l:
            in:
                type: list
                args: [T]
```

---

Related to https://github.com/emil14/neva/issues/62 and https://github.com/emil14/neva/issues/43
