### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by emil14** [nevalang/neva#45]
# Direct dependency

```
# root
deps;
  root: ...
workers:
  self: root

# pkg
scope:
  root: root
```

Current implementation of `generator` will stuch in an endless loop:

1. create `self` worker for `root`
2. since it's not an operator put its dep (root) in the queue
3. take the element from the queue
4. ...
5. it's root again, go to step 1

# Indirect cycle dependency

It's possible to create package where `a` depends on `b` while `b` depends on `a`:

```yml
# a

deps:
 x: ...
workers:
  xw: x

# b

deps:
  y: ...
workers:
  yw: y

# pkg.yml

scope:
  x: b
  y: a
```

Which will lead to endless loop in a runtime-program generation step:

1. To create `xw` worker for any instance of `a` component we need to create an instance of `b`
6. To create `yw` worker for any instance of `b` component we need to create an instance of `a`
7. Go to first step

---

Related to #46 (recursion of components)
