### ISSUE TITLE
Null value

### ISSUE THREAD

**Issue by emil14** [nevalang/neva#51]
For recursive data-structures with direct or indirect struct-based cycles there must be a way to tell "this time recursion stops". In other words it's not a problem for type like this:

```
node:
  id: int
  children: [node] # <- indirect list based self reference

node:
  id: int
  children: map[string]node # <- indirect map based self reference
```

But it is for this:

```
node:
  id: int
  left: node # <- direct self reference
  right: node
```

Or

```
node:
  id: int
  child:
    meta: string
    value: node # <- indirect struct-based reference
  
```

Because we need something like `left: node?` or `left: node | nil`. 

Also questions that must be answered:

- should we have special `null` type or `null` is a valid value for some (all?) existing types?

---

TODO: think if this problem  exist for substreams
